/***peliculas */

/**OBTENER TODOS LAs PELICULAS */
export const COMENZAR_DESCARGA_PELICULAS = 'COMENZAR_DESCARGA_PELICULAS'
export const DESCARGA_PELICULAS_EXITO = 'DESCARGA_PELICULAS_EXITO'
export const DESCARGA_PELICULAS_ERROR = 'DESCARGA_PELICULAS_ERROR'

/** INFORMACIÓN DE UNA PELICULA PARA VER EL DETALLE */
export const OBTENER_PELICULA_DETALLE = 'OBTENER_PELICULA_DETALLE'
export const PELICULA_DETALLE_EXITO = 'PELICULA_DETALLE_EXITO'
export const PELICULA_DETALLE_ERROR = 'PELICULA_DETALLE_ERROR'

/**OBTENER EL CAST DE LA PELICULA */
export const OBTENER_PELICULA_CAST = 'OBTENER_PELICULA_CAST'
export const PELICULA_CAST_EXITO = 'PELICULA_CAST_EXITO'
export const PELICULA_CAST_ERROR = 'PELICULA_CAST_ERROR'

/**OBTENER PELICULAS SIMILARES */
export const OBTENER_PELICULA_SIMILAR = 'OBTENER_PELICULA_SIMILAR'
export const PELICULA_SIMILAR_EXITO = 'PELICULA_SIMILAR_EXITO'
export const PELICULA_SIMILAR_ERROR = 'PELICULA_SIMILAR_ERROR'

/**BUSCAR PELICULAS */
export const OBTENER_PELICULAS_BUSCAR = 'OBTENER_PELICULAS_BUSCAR'
export const PELICULAS_BUSCAR_EXITO = 'PELICULAS_BUSCAR_EXITO'
export const PELICULAS_BUSCAR_ERROR = 'PELICULAS_BUSCAR_ERROR'
