/***peliculas */

/**OBTENER TODOS LAs PELICULAS */
export const COMENZAR_DESCARGA_PELICULAS = 'COMENZAR_DESCARGA_PELICULAS'
export const DESCARGA_PELICULAS_EXITO = 'DESCARGA_PELICULAS_EXITO'
export const DESCARGA_PELICULAS_ERROR = 'DESCARGA_PELICULAS_ERROR'

/** INFORMACIÓN DE UNA PELICULA PARA VER EL DETALLE */
export const OBTENER_PELICULA_DETALLE = 'OBTENER_PELICULA_DETALLE'
export const PELICULA_DETALLE_EXITO = 'PELICULA_DETALLE_EXITO'
export const PELICULA_DETALLE_ERROR = 'PELICULA_DETALLE_ERROR'