/***peliculas */

export const COMENZAR_DESCARGA_PELICULAS = 'COMENZAR_DESCARGA_PELICULAS'
export const DESCARGA_PELICULAS_EXITO = 'DESCARGA_PELICULAS_EXITO'
export const DESCARGA_PELICULAS_ERROR = 'DESCARGA_PELICULAS_ERROR'

